apiVersion: devsecops.io/v1alpha1
kind: CanaryDeployment
metadata:
  name: auth-service-canary
  namespace: default
spec:
  targetDeployment: auth-service
  serviceName: auth-service
  canaryImage: nginx:1.27-alpine
  canaryReplicas: 1
  prometheusUrl: "http://prometheus-k8s.monitoring.svc.cluster.local:9090"
  rolloutSteps: [5, 10, 25, 50, 100]
  intervalSeconds: 30
  thresholds:
    maxErrorRatePercent: 0.5
    maxP99LatencySeconds: 0.250